"use client";
import localFont from "next/font/local";
import "./globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript } from "@mantine/core";
import { createTheme, MantineProvider } from "@mantine/core";
import Layout from "@/components/layout/Layout";
import React, { useEffect, useState } from "react";
import { FallingLines } from "react-loader-spinner";

import "@/i18n";
import { useTranslation } from "react-i18next";
import { changeLanguage } from "i18next";

// import { Roboto } from "next/font/google";
// import { Noto_Naskh_Arabic } from "next/font/google";

const theme = createTheme({
  /** Put your mantine theme override here */
});

const roboto = localFont({
  src: "./fonts/Roboto-VariableFont_wdth,wght.ttf",
  variable: "--font-roboto",
  weight: "400",
});
const noto = localFont({
  src: "./fonts/NotoNaskhArabic-VariableFont_wght.ttf",
  variable: "--font-noto",
  weight: "400",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { t, i18n } = useTranslation();

  const [language, setLanguage] = useState("");

  // console.log(window);

  const [loader, setLoader] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setLoader(false);
    }, 3000);
  }, []);

  useEffect(() => {
    i18n.changeLanguage(navigator.language);
    setLanguage(clientInformation.language);
  }, []);

  return (
    <html lang={`${language}`} dir={language === "en" ? "ltr" : "rtl"}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        {/* <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        /> */}

        <title>Sarok Resume</title>

        <ColorSchemeScript />
      </head>
      <MantineProvider theme={theme}>
        <body
          className={`${roboto.className} ${noto.className}   antialiased w-screen h-screen  flex justify-center items-stretch text-center lg:px-36  overflow-hidden bg-[url('image/blackandwhite2.jpg')]`}
        >
          {loader ? (
            <div className="flex justify-center items-center ">
              <FallingLines
                color="#e5383b"
                width="200"
                visible={true}
                ariaLabel="falling-circles-loading"
              />
            </div>
          ) : (
            <Layout setLanguage={setLanguage}>
              <div className="w-full h-full motion-preset-slide-right max-[630px]:w-screen  max-[630px]:h-screen">
                {children}
              </div>
            </Layout>
          )}
        </body>
      </MantineProvider>
    </html>
  );
}
