import localFont from "next/font/local";
import "./globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript } from "@mantine/core";
import { createTheme, MantineProvider } from "@mantine/core";
import Layout from "@/components/layout/Layout";
// import blackandwhite from "@/app/image/black and white.jpg";

const theme = createTheme({
  /** Put your mantine theme override here */
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        {/* <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        /> */}

        <title>Sarok Resume</title>

        <ColorSchemeScript />
      </head>
      <MantineProvider theme={theme}>
        <body
          className={`${geistSans.variable} ${geistMono.variable}  antialiased w-screen h-screen  flex justify-center items-stretch text-center px-36 py-28 overflow-hidden bg-[url('image/blackandwhite2.jpg')]`}
        >
          <Layout>{children}</Layout>
        </body>
      </MantineProvider>
    </html>
  );
}
